spring:
  application:
    name: user-center
  datasource:
    #type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/timess
    username: root
    password: "099636"
  #session失效时间
  Session:
    timeout: 86400
